### ISSUE TITLE
Support for https://www.ben-evans.com/essays

### ISSUE THREAD

**Issue by sogen** [kickscondor/fraidycat#139]
* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser [N/A], using desktop app.
 - Version: 1.1.5
 - URL you are attempting to follow: https://www.ben-evans.com/essays

**Describe the bug**
Page is not detected as expected, instead it suggest two individual posts as its feed.

**Comment by kickscondor** [comment]
Ok - interesting. This page doesn't have a feed attached. But it's detecting the word 'feed' in two of the blog posts, which is its best guess at a feed.

But the best part is that if you subscribe to one of them, it works out. Because the posts themselves have the correct feed.

I'm not sure how to handle this. If the page you're trying to subscribe to doesn't have a feed, I can't really assuming that automatically going up to https://www.ben-evans.com/ or down through one of the posts will give the correct feed. I kind of feel like this is working right. Got a better idea? (Thanks for the bugs, sogen.)

**Comment by sogen** [comment]
thanks,
selected one of the feeds and it worked :)


About how to handle it, One option I can think of:  
Select one of the working feeds automatically, without user intervention.

Longer explanation:
1. User enters https://www.ben-evans.com/essays 
2. clicks Save
3. (this step is not visible to the user) The first feed is automatically selected by the app
4. User is back to Fraidycat
I think this would need some sort of "white list", maybe unfeasible for the current state of the web with triilllions of websites.

Or a simpler option:
Display a message such as "no official feed found, try selecting one of these and see if it works ;)"

**Comment by kickscondor** [comment]
Ok, good - really appreciate the suggestions. I think you're right that I need to at least improve the text of that page to indicate that these are only guesses at the real feed's location.

I think you should also contact the owner of this site, to include the following tag on https://www.ben-evans.com/essays:

    <link rel="alternate" type="application/rss+xml" title="RSS Feed" href="https://www.ben-evans.com/benedictevans?format=rss">

I'm definitely okay trying to work around this kind of thing - which is why Fraidycat attempts to find 'feed' links on the page. But it's not yet to the point where I can intuit where the feed is by spidering the site.

**Comment by kickscondor** [comment]
Ok, the wording has changed and this is being covered in greater detail in #67.
