### ISSUE TITLE
Support for https://mckltype.com/news/

### ISSUE THREAD

**Issue by sogen** [kickscondor/fraidycat#141]
* [X] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser N/A
 - Version 1.1.5
 - URL you are attempting to follow [if applicable]: https://mckltype.com/news/

**Describe the bug**
Can't find a RSS/Atom feed to add.

**Comment by kickscondor** [comment]
Ok interesting. I don't personally want to add this - because then I have to maintain it and test it with every release and worry about it breaking. And there are good reasons to contact this website to ask if they can add an RSS feed.

However, I understand that users will want to access all kinds of websites. (See #67.) It would be to have an additional list of websites that are not official supported. So let's hold on to this and see what we can do.

**Comment by kickscondor** [comment]
Ok, see #67 for more on this topic.
