### ISSUE TITLE
Support for Pocket / Reading Lists

### ISSUE THREAD

**Issue by adilosa** [kickscondor/fraidycat#151]
**Before you start.**

* [x ] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
It would be great if Fraidycat had a way to save links to a Reading List to be viewed later. Perhaps a little icon that could save to Pocket or another read-it-later provider.

I often use my source-aggregators to build up a reading list of interesting articles that are too long or in-depth to blow through right away.

**Comment by kickscondor** [comment]
Ok interesting. This is good to keep in mind for the upcoming richer post view in #30. I am not going to add an icon next to every title - because that would clutter up the display with an icon that most users will not use. However, I can display icons in the richer post view. (BTW are you using the browser extension or the app?)

I also wonder if there is a good extension to recommend here - perhaps one that adds "Share to Twitter", "Share to Reddit" etc. for the right-click. Because I can imagine people requesting all kinds of targets to send a link to. https://chrome.google.com/webstore/detail/save-to-pocket/niloccemoadcdkdjlinkgdfekeahmflj?hl=en

**Comment by kickscondor** [comment]
I don't know - just making lists here.
https://chrome.google.com/webstore/detail/addtoany-share-anywhere/ffpgijchhhkhnokafdeklpllijgnbche

**Comment by adilosa** [comment]
Sounds good. That makes sense to put it in the richer view. 

I don't know of a good plugin to support multiple share sites, but that seems like a good idea. The Pocket macOS app has a share button which looks similar to the plugin you linked: 
![image](https://user-images.githubusercontent.com/2894907/83570810-8edf1880-a4db-11ea-9d4d-ca89abfeb710.png)
It's also a relatively common pattern on Mac/iOS to have a system Share Sheet which can send stuff to various apps, and that works out nicely. 

Also, I typically use the app as I'm not much of an extensions user. However, without an inline post viewer, all the links just open Chrome anyway – so I'm trying to get used to using the extension.

**Comment by kickscondor** [comment]
This discussion has moved to #153, which is a more general solution to this issue.
