### ISSUE TITLE
Twitter updates get frozen

### ISSUE THREAD

**Issue by mpancorbo** [kickscondor/fraidycat#152]
**Before you start.**

* [x ] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Also: Appimage and debian package
 - Version [1.1.5]

**Describe the bug**

I mainly use Fraidycat for twitter fellows and since yesterday (2020-06-02) all twitter accounts does not update and their avatar is replaced by twitter's bird one. I follow other people through proxies like nitter.net and these ones update normally.

**Comment by mitchellgordon95** [comment]
My Twitter feeds have also not been updating since two days ago. Interesting because I'm on Chrome, not Firefox.

OS: macOS High Sierra 10.13.6
Browser: Chrome Version 81.0.4044.129 (Official Build) (64-bit)
FraidyCat: 1.1.5

Let me know if you need me to do any debugging, logs, etc, have some webdev experience.

**Comment by kzys** [comment]
It seems `https://twitter.com/[username]` no longer have tweets. Switching to `https://mobile.twitter.com/[username]` may work, since it has tweets still.

**Comment by mpancorbo** [comment]
> My Twitter feeds have also not been updating since two days ago. Interesting because I'm on Chrome, not Firefox.

No surprise. My report includes two desktop apps not working (debian package and Appimage).

> It seems `https://twitter.com/[username]` no longer have tweets. Switching to `https://mobile.twitter.com/[username]` may work, since it has tweets still.

Also switching to `https://niitter.net/[username]` works, but that's not the point; the app does not allow to change the source, so you must re-input all twitter sources what is annoying. 

I guess the problem sides on some change around how twitter manage manage RSS.

**Comment by kzys** [comment]
Sorry. I meant switching to `mobile.twitter.com` *internally*. Twitter doesn't have RSS and Fraidycat uses https://github.com/kickscondor/fraidycat/blob/c077f3193dc1960c6d224a6082d01f0a96fe4ad3/defs/social.json#L496 to fetch its HTML. Updating the JSON file (including XPath selectors) would work, I suppose.

**Comment by kickscondor** [comment]
I am working frantically on this. As @kzys mentions, I have tried switching to mobile.twitter.com, but there are no precise timestamps. Still, it could be good enough. I'm attempting to use the rendering approach (currently used with TikTok) to use the old rule set.

This is going to happen from time to time, because I try not to rely on APIs (which are rate-limited) - however, I am able to update the scraper (or even to support APIs) without requiring any of you to update the software or to re-enter your follows.

Thank you for caring enough to come here and offer useful info!

**Comment by kickscondor** [comment]
Ok, so Nitter dealt with this a few days ago too: https://github.com/zedeus/nitter/issues/157

I'm mimicking their same strategy. Almost there. I'm sorry for the delay. Twitter is a bit more complicated than other platforms because I also collapse Twitter threads.

**Comment by httpsterio** [comment]
Rate-limited APIs wouldn't be an issue though, if each user gets their own API keys. I doubt even a heavy user would ping their API hard enough to get rate limited

**Comment by kickscondor** [comment]
Ok, this appears to be fixed. Your feeds should update in the next hour. Let me know how it goes!

I was able to make some improvements with the new calls:

* Retweets are now shown at the time of retweet (not at the time of original posting, as was the case previously.)
* Text layout is improved (because it's using Twitter's raw text, rather than an HTML-to-text conversion.)
* I now have access to richer post information, for when the rich post view is done.

Thank you for being patient so that I could do this properly.

**Comment by mpancorbo** [comment]
Yes, it seems it works o_O

But... how? My app/plugin is not updated.
