### ISSUE TITLE
Data fetching progress bar or last updated timestamp

### ISSUE THREAD

**Issue by stevenirby** [kickscondor/fraidycat#154]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

It would great if Fraidycat had a progress bar or some way to indicate when it's done updating and fetching data. Every week I notice the data gets cached and it stops updating. I mentioned a hack I use to get it to start fetching data again here: #92 

It would help to see when data isn't updating anymore, or if it is working, how much longer until it's up to date.

**Comment by kickscondor** [comment]
Ok - this should be out on Monday if all goes well. Thank you!

**Comment by kickscondor** [comment]
Yeah - wow. So this is a rather stunning admission - and perhaps everyone who stumbles across this will immediate bail on my tools - but this wasn't working because I commented out a single line of code. (In [67c82a6f](https://github.com/kickscondor/fraidycat/commit/67c82a6f1a932648a5823883dab93e44e8f75402#diff-73ef8c4664f2ec8c02320d50b2908efdR182).) It's been disabled for nearly four months!

I've reversed it and yet the stain remains.
