### ISSUE TITLE
Twitch feeds no longer updating.

### ISSUE THREAD

**Issue by badgersaurus** [kickscondor/fraidycat#242]
**Before you start.**
* [x] I have checked the [Common Problems](https://github.com/kickscondor/fraidycat/wiki/Common-Problems) page.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A (on standalone desktop version)
 - Version 1.1.7

**Describe the bug**
I follow a few Twitch streamers on Fraidycat. I'm not sure exactly when, but the feeds no longer update with recent streams or show when the streamer is live. The last time it worked properly was 9 days ago, apparently, but since none of the streamers I follow stream daily this may not be accurate.

**Comment by Nogooduser** [comment]
I also get a 401 error when trying to follow twitch streamers.

As a workaround until this is fixed, I found that using [Twitch RSS](https://twitchrss.appspot.com/) works well enough to get a feed link.

**Comment by omentic** [comment]
I think this is caused by an outdated OAuth token. Switching it out in social.json should fix the problem. 

Looking through the code, it looks like Fraidycat redownloads social.json once an hour from this url: https://huh.fraidyc.at/defs/social.json

I don't think there's any way to update social.json within the extension that won't get overwritten by it redownloading the outdated version, unfortunately.

**Comment by omentic** [comment]
Thank you @kickscondor - Twitch feeds are working again!

**Comment by kickscondor** [comment]
@j-james Of course - sorry for the long wait.
