### ISSUE TITLE
Twitter/Reddit URLs don't work with Firefox 'Strict' Tracking Protection

### ISSUE THREAD

**Issue by kickscondor** [kickscondor/fraidycat#26]
From ValdikSS:

> Hi, letting you know that Fraidycat for Firefox doesn't work if strict tracking protection is enabled in Firefox settings. The extension console writes the following:
> 
> The resource at “https://www.reddit.com/r/linux/” was blocked because content blocking is enabled.
> _generated_background_page.html
> Error: NetworkError when attempting to fetch resource. webext.js:177:22
> 
> The extension does not show any error, just hangs indefinitely when "save" button is pressed.

After getting some blog URLs to work and replying to ValdikSS - another reply came in:

> I've tested only twitter and reddit urls, both are blocked. I assume that Firefox considers requests from websites or extensions to only some third-party huge and well-known websites as trackers, that's why standalone blogs on custom domains work fine.

Work to do.

**Comment by lucible** [comment]
Just ran into this issue (I think) when trying to add a follow for a twitter account. I used RSS Box to make it a feed, and that worked. When I try to add the URL by itself, I get `Error: NetworkError when attempting to fetch resource.` in the console.

In general, I also get this error when I open FraidyCat: `The resource at “https://twitter.com/favicon.ico” was blocked because content blocking is enabled.` which is why I think my twitter URL issue is related to the Firefox 'Strict' Tracking

**Comment by kickscondor** [comment]
I am also getting similar behavior in Chrome on a Chromebook.

**Comment by 7415963987456321** [comment]
A workaround for FF that could work for now, you can disable the strict tracking protection per site, so it suffices to click on the shield icon in the address bar and then you will have whitelisted freidycat.

**Comment by mybuddymichael** [comment]
Alas, disabling tracking protection just for fraidyc.at does not work for me. I have to turn off all protection in Firefox's preferences. 🙁

**Comment by kickscondor** [comment]
This is now being worked on in #113.
