### ISSUE TITLE
Tag defaults to "Real-time" view even if there are no sources in Real-time

### ISSUE THREAD

**Issue by joshuacwnewton** [kickscondor/fraidycat#32]
If I have a tag where every source is Daily/Weekly/Monthly/Year (in other words, no source in the tag has Real-time importance), then Real-time still shows as a tab, and remains the default view. 

![test1](https://user-images.githubusercontent.com/16181459/70929626-5b213c80-1fe8-11ea-997f-eee909fa3da1.png)

As soon as the "Weekly" tab is clicked, the "Real-time" tab becomes unclickable. 

![test2](https://user-images.githubusercontent.com/16181459/70929625-5a88a600-1fe8-11ea-81ba-967ee3c5cb3f.png)

My guess is that it could be better to default to whatever is next in the hierarchy of Daily > Weekly > Monthly > Year and hide Real-time entirely?

_(Thanks again for maintaining this lovely project, kicks!)_

**Comment by kickscondor** [comment]
So, yes, I realize this is a bit confusing and strange. :) However, this is the intended behavior. (It actually used to work just like you describe back in version 1.0.) Heh.

* Because the blue and green highlights on the tab correspond to 'real-time' follows, I want to make it obvious why the tab isn't highlighting when you have no 'real-time' items. If you see that a tab is blank and you're like "What??? There's stuff in there!", then you click in and see no 'real-time' follows, you'll go, "Oh, yeah, that's right."
* Because 'daily', 'weekly', 'yearly' stuff shouldn't be checked as frequently, this requires an extra step to get to them - it ensures that they stay out of the way until you really need them.

I may be convinced to change this - I am not sure that it's quite right yet. Feel free to weigh in further.

**Comment by joshuacwnewton** [comment]
That makes sense! Thanks for being open about the intended behavior. :)

>Because 'daily', 'weekly', 'yearly' stuff shouldn't be checked as frequently, this requires an extra step to get to them - it ensures that they stay out of the way until you really need them.

I only ever click on the non-highlighted tabs rarely anyways (because I've come to understand that those tabs only have things I should check rarely, and there's no UI incentive for me to check them.) So for me, I'm not sure the extra disincentive is necessary. 

But, then again, maybe I underestimate my checking behavior? I might try to live with this idea for a while to see how it feels. I've changed my mind before... (see the other issues I've raised, you always make very good points!)

**Comment by kickscondor** [comment]
Ok thank you for understanding - let's chat again in a week.

**Comment by joshuacwnewton** [comment]
>Because the blue and green highlights on the tab correspond to 'real-time' follows, I want to make it obvious why the tab isn't highlighting when you have no 'real-time' items. If you see that a tab is blank and you're like "What??? There's stuff in there!", then you click in and see no 'real-time' follows, you'll go, "Oh, yeah, that's right."

Perhaps one suggestion could be to have a different tab color for "no follows being tracked"? That would make 4 colors:

1. **Green:** Real-time follows have updated in last few days.
2. **Blue:** Real-time follows have updated in last few weeks.
3. **Brown:** Real-time follows have updated in last months/years. _(New)_
4. **Neutral/pinkish/salmon:** No real-time follows in tag.

Right now, neutral/pinkish highlights are doing double duty for categories 3/4, and there's no distinction between them.

**Comment by kickscondor** [comment]
I've just had a suggestion that one simple tweak here is to just make the 'real-time' link clickable even when there's nothing there. I will do that for now - but I'm hoping I can make your suggestion (default to highest frequency) fit somehow.

**Comment by joshuacwnewton** [comment]
No pressure! It's your project, and I only hope to make suggestions if they fit your usage habits too. If my idea isn't helpful for you, feel free to shut me down, hehe. :)

**Comment by kickscondor** [comment]
Ok, I think I've come up with an answer.

* When you click on a tag, it'll take you to the highest 'importance' that contains follows. (In your screenshot above, you would go to 'Weekly'.)
* 'Real-time' is available and clickable - to indicate that you have none. (To avoid confusing about tab highlighting.)
* Empty 'real-time' tabs will show the basic Fraidycat intro text ("This is empty! Add follows here...") and will also note that 'real-time' follows cause the tab highlighting.

I like this solution because I don't want people to have to read docs to learn Fraidycat - but I can use this page to clear up some things.
