### ISSUE TITLE
author link points to the linked Atom XML instead of the user-provided URL

### ISSUE THREAD

**Issue by teepark** [kickscondor/fraidycat#52]
**Desktop**
 - OS: Mac
 - Browser Firefox
 - Version 1.0.6

**Describe the bug**
After adding the URL of a blog which has an atom feed, the author link on the main fraidycat page points to the atom XML link instead of the original URL added.

The blog at https://danluu.com/ illustrates the bug. In this case, https://danluu.com/ is a valid HTML link that works in a browser, https://danluu.com/atom/index.xml does not.

Screenshots below:

---

**adding the follow:**
![Fraidycat](https://user-images.githubusercontent.com/37182/71136802-d6d2e300-21ba-11ea-8585-6b38762a1469.png)

**main page, while hovering over "Dan Luu 📓" link:**
![Screen Shot 2019-12-18 at 5 23 10 PM](https://user-images.githubusercontent.com/37182/71136910-2fa27b80-21bb-11ea-8e0c-ca9963fade93.png)

**Comment by kickscondor** [comment]
Ok great. Yeah the problem here is that the feed has that address in the main 'link' tag. Should be the blog's canonical address.

However, I am considering moving away from that tag - for other reasons. Still, if you use the feed address directly (http://danluu.com/atom.xml), the address will definitely be wrong. So I would also appeal to the site's owner, they'll probably appreciate it. (As I appreciate your report! 😘)
