### ISSUE TITLE
Show expanded feed view by default

### ISSUE THREAD

**Issue by mpern** [kickscondor/fraidycat#62]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**

Add a new setting/option:

"Show expanded list" (or sth similar)

For low-frequency feeds, my usual workflow looks like this:

1. Open list of feeds
1. Scroll through list, Click "Expand" button for every feed one by one
1. Scroll through list again and look for interesting headlines

It would be nice to have a toggle in the settings to show the expanded list by default.

**Comment by kickscondor** [comment]
Mmm - I see why this could be useful. I will have to think about this. The main trouble is that, again, some feeds may come to dominate the page due to length titles. (Tweets, for instance, are shown as the full text, since they have no titles.)

I am working on revising the 'feed view' ('post view') design - somewhat discussed in #30 (and to try to address #50) - so if I am successful in presenting a nicer layout, then I could absolutely see this being a feature. (This will also need to be done once I have added a richer settings page and the code to sync settings.)

Thank you for the suggestion!

**Comment by kickscondor** [comment]
Okay - after giving this some thought, I think I have a compromise. I would like to add an "expand all" button to each page, which you can click to toggle open all of the posts on every page while you browse. I will probably also see how it feels to have it persist that view even if the main window closes.

I am not sure about this feature at all yet - so I can't guarantee that it will make it - but I think it could be cool! I guess we'll see...

**Comment by mpern** [comment]
Expand all + persistent state sounds good enough for me 🤷‍♂

**Comment by kickscondor** [comment]
Okay this will be out in 1.1.0 later today. There is an option 'Expand All' in the new view dropdown. I think it worked out nicely! Please reopen this if there are further issues.
