### ISSUE TITLE
Base an item's relative age on its creation time, not its modification time

### ISSUE THREAD

**Issue by jmacdotorg** [kickscondor/fraidycat#64]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
I believe that Fraidycat would present a better experience if it based its concept of an item's relative age by its creation time rather than its last-modified time, which is apparently how it reckons age currently.

I have so far found two cases where its current behavior seems sub-optimal:

* Blogs with active comment-sections that are configured to update a post's modification date every time a new comment appears on that post. This causes Fraidycat to treat the blog as if it is posting constantly, requiring a downshift in "importance" to daily or weekly -- even if the blog actually features only a few posts every month.

* I am one of those bloggers who enters a lengthy period of fiddling and self-editing that can last as long as a day or two after publishing a particularly meaty post. Sometimes this cascades into my reaching back and tweaking older posts that the first post mentions. This causes Fraidycat to treat all these edit as worthy of attention as these posts' original publication -- and it just ain't so. I dare say that this holds true with every other blog as well.

    (Certainly, I feel pretty self-conscious and spammy when I see my own post undeservedly floating at the top of my own Fraidycat view, just because I keep going back to fix typos or add a couple more hyperlinks or whatnot!)

**Comment by kickscondor** [comment]
First off, thank you for the detailed post you wrote - you really get what this project is about! I particularly appreciate the suggestion you made there and in these two reports here on Github. I feel like Fraidycat is a long way from what it could be - but it is difficult to feel out the way to go - and to be careful about it not turning into a bloated or misdirected piece of software.

Even for myself, it is not the tool I am satisfied with yet. It is promising - but it still has a lot of problems. Sometimes it is slow still, sometimes the timing of its fetches feels wrong, the organization is overly simplistic, it goes on and on - I myself struggle to make it the tool I really want. I am actually surprised that you have been using it - because I still see it as such a simplistic prototype.

Yes, so this particular issue is a difficult one and is both a problem with RSS feeds and with Fraidycat.

On one hand, I want to know when posts are edited and updated. Part of getting away from chronologies that simply push posts into the past is the 'updated' date. With TiddlyWikis this works great! The wikis that I watch often updated old pages and I want to be aware of that. This perspective treats a post as a draft that is continually modified over time - and draws my attention back to important posts on a website.

But the other side is what you describe. And I have already been through this with YouTube in #20. The modification dates on YouTube are always changing when someone updates a title or something - so it's confusing to people. I ended up ignoring its modification times.

So - how to move forward?

* Perhaps I allow updated posts to show up in the post view, but I don't allow them to cause the blog itself to shoot to the top of the list. (This definitely needs to happen, because this seems like an exploit - someone could constantly update an RSS entry's 'update' time to keep their blog pegged to the top.)
* Or, perhaps this becomes a setting on each blog. ("Watch for updates?") I don't like this because I feel that custom settings should be very minimal - it creates too much of a testing burden for me.
* Or perhaps I drop 'updated' times all together. I don't feel this is an option, because I find them useful.
* Maybe I require a custom 'major edits' updated time extension for RSS? I know this seems like the worst option of all!! However, I actually am going to introduce some RSS extensions for Fraidycat that make a lot of sense - it's possible that this could be one as well. (The field could be like 'republished' - still I would need to couple this with a solution above.)
* Perhaps I could provide a 'view' that shows updates and a 'view' that does not (similar to what is happening in #62). Right now this is the option that I like the best - but I still need to try out these new 'views' to see how they feel.

I hope some of this makes sense. I am going to ponder this further - but thank you very much for your thoughtful work, Jason!

**Comment by kickscondor** [comment]
Ok, I've settled on the last option for now. In the new view selector (right-hand side of the page, under the tabs), there's an option 'Show Post Updates' that will respect edits to posts. The default is to ignore them, however. Should be out soon. Reopen this if there are issues with it or if I'm way off on this.
