### ISSUE TITLE
Do fraidycat really need all these permissions?

### ISSUE THREAD

**Issue by tcgumus** [kickscondor/fraidycat#65]
**Before you start.**

* [x] I have checked the [Rejected Features](https://github.com/kickscondor/fraidycat/wiki/Rejected-Features) page.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**My great idea for Fraidycat is:**
![image](https://user-images.githubusercontent.com/2714346/74470533-cafc5800-4eaf-11ea-976a-10b7c2edef9a.png)

Please change it for a more reasonable permissions list if possible.
Best regards,
Tuna

**Comment by kickscondor** [comment]
Yes - this is a very serious problem - I'm working on this in issue #51 

Unfortunately, I'm now having to add _more_ permissions (webRequest and webRequestBlocking) in order to get actual asynchronous fetch to work without blocking the entire extension. Hopefully I can take a step forward on this soon, but I'm not hopeful.

**Comment by tcgumus** [comment]
Thank you for the response. I think i can close this since this is already recognized.
