### ISSUE TITLE
[Firefox Extension] Clicking Fraidycat icon opens a blank page

### ISSUE THREAD

**Issue by eli-oat** [kickscondor/fraidycat#71]
**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Firefox 73.0
 - Version Fraidycat v1.1.0

**Describe the bug**
After updating to version 1.1.0 whenever I click the Fraidaycat extension icon in Firefox's toolbar I'm taken to <https://fraidyc.at/s/> instead of the click launching the extension.

**Comment by kickscondor** [comment]
This is actually correct - this new URL is where the app lives. (My testing revealed that this increased performance dramatically, see #1 for more.)

However, I'm guessing the issue is that you're getting a blank page? My main delay over the past week has been resolving this bug on Firefox - and I really thought I had squashed it.

**Comment by eli-oat** [comment]
Ah. Sorry for my confusion! 

You are right. I am getting a blank page. 

In a bit I can test on some other hardware.

**Comment by kickscondor** [comment]
I really appreciate you reporting this. The way to catch the problem is like so:

1. While the extension is running, open `https://fraidyc.at/s/` in a new tab.
2. Open the Debugger in dev tools. (Menu > Web Developer > Debugger.)
3. In the bottom pane, there should be a *Breakpoints* area.
4. Make sure *Pause on exceptions* is checked.
5. Reload the page. The debugger should pause on the exception that is thrown. I believe the exception should appear above the *Breakpoints* pane. Take a screenshot and post it here.

I apologize for the difficulty - I really thought I had done sufficient testing on this one.

**Comment by eli-oat** [comment]
> I apologize for the difficulty - I really thought I had done sufficient testing on this one.

No worries at all! I am happy to help. 

Here is a screenshot of the debug output.

![Screen Shot 2020-02-25 at 10 27 37 AM](https://user-images.githubusercontent.com/3342274/75261745-85962f80-57b9-11ea-90bb-b62bb9a7129a.png)

**Comment by eli-oat** [comment]
Whilst not a definitive proof, it looks like the issue *may* be confined to macOS? Running the same version of Firefox on Alpine Linux everything is working splendidly. 

![Screen Shot 2020-02-25 at 10 33 21 AM](https://user-images.githubusercontent.com/3342274/75262423-82e80a00-57ba-11ea-8d24-3bd8470c1f29.png)

**Comment by kickscondor** [comment]
Ok, wonderful - I believe I can solve this quickly. No, it's very strange - I personally experienced the problem on WIndows but not Mac. Chances are that it has more to do with using an existing set of follows under 1.1 than a platform bug. Had you been using the Linux Firefox before today?

**Comment by eli-oat** [comment]
I had been using it. But not for long. Maybe a day? It is a new vm.

**Comment by kickscondor** [comment]
Ok - I've solved this. It had to do with some Babel settings. I'm just running through my tests to be sure I haven't messed up anything else.

**Comment by eli-oat** [comment]
Awesome! 

Sorry I wasn’t at a computer most of today to be more helpful. I’ve been wanting to hack on fraidycat but haven’t had the time to sort out the build system for local dev.

**Comment by eli-oat** [comment]
Confirmed fix! Thanks
