### ISSUE TITLE
1.1.0 - Frequent and Occasional Lists Gone?

### ISSUE THREAD

**Issue by joejenett** [kickscondor/fraidycat#72]
Firefox 73.0.1 on mac (Catalina)

If I click on Frequent or Occasional in the menu, nothing happens.
I tried adding a new feed to the Occasional list, got the "following" message and tried again and the problem still exists.

**Comment by kickscondor** [comment]
Shoot - so, this is a problem with certain follows under 1.1.

If you can export your follows to a JSON and attach it here, that would help me immensely.

You might be able to resolve this from your end by removing the Fraidycat extension and reinstalling it. (If you are logged into Firefox, it should reload them all. But I would still export a copy of them in case there is an issue.)

Thank you so much for letting me know about this! I knew this week would be a rough transition, because so much has changed.

**Comment by joejenett** [comment]
I’m attaching the .json file via my mail client as that format wasn’t accepted when I tried to attach it via replying on the issues page - hope it works.



I’ll try removing and reinstalling the extension and will let you know if it resolves the issue.

cheers

**Comment by kickscondor** [comment]
Yes - I just got it. Thank you! I've been able to reproduce this. :)

This turns out to be the same issue that Eli is seeing in #71. I'm so glad you two have helped me track this down! Fortunately, when I update the Firefox extension, it should be approved immediately.
